import { imageManifest } from "../data/imageManifest";

interface Props {
  /** Public path to the source raster, e.g. "/case-studies/lila-trips/hero.jpg". */
  src: string;
  alt: string;
  className?: string;
  loading?: "lazy" | "eager";
  /** Hint for high-priority above-the-fold images. */
  fetchPriority?: "high" | "low" | "auto";
}

const RASTER = /\.(png|jpe?g)$/i;

/**
 * Responsive image: serves a resized WebP (generated by scripts/optimize-images.mjs)
 * with the original raster as a <picture> fallback, and applies intrinsic
 * width/height from the manifest so the layout reserves space (no CLS).
 * The <picture> is display:contents, so the <img> lays out exactly as before.
 */
export default function Img({ src, alt, className = "", loading = "lazy", fetchPriority }: Props) {
  const dims = imageManifest[src];
  const webp = src.replace(RASTER, ".webp");
  const hasWebp = webp !== src;

  return (
    <picture style={{ display: "contents" }}>
      {hasWebp && <source srcSet={webp} type="image/webp" />}
      <img
        src={src}
        alt={alt}
        loading={loading}
        decoding="async"
        fetchPriority={fetchPriority}
        width={dims?.width}
        height={dims?.height}
        className={className}
      />
    </picture>
  );
}
