/**
 * Image optimization — generates resized WebP derivatives next to each raster
 * source in public/, plus a dimensions manifest for CLS-free rendering.
 *
 * Non-destructive: the original PNG/JPG stays as a <picture> fallback. Only the
 * .webp derivatives (served to ~97% of browsers) and the manifest are produced.
 * WebP files are gitignored and regenerated on build; the manifest is committed
 * so `Img` has dimensions in dev too. Rerun after adding/replacing images:
 *   npm run optimize:images
 */
import { readdir, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import path from "node:path";
import sharpFn from "sharp";

const ROOTS = ["public/case-studies", "public/images"];
const MAX_WIDTH = 1600;
const WEBP_QUALITY = 80;
const RASTER = /\.(png|jpe?g)$/i;

async function walk(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else if (RASTER.test(entry.name)) out.push(p);
  }
  return out;
}

const files = [];
for (const root of ROOTS) files.push(...(await walk(root)));
files.sort();

const manifest = {};
let originalBytes = 0;
let webpBytes = 0;

for (const file of files) {
  const meta = await sharpFn(file).metadata();
  const targetW = Math.min(meta.width, MAX_WIDTH);
  const outH = Math.round((meta.height * targetW) / meta.width);
  const webpPath = file.replace(RASTER, ".webp");

  const info = await sharpFn(file)
    .resize({ width: targetW, withoutEnlargement: true })
    .webp({ quality: WEBP_QUALITY })
    .toFile(webpPath);

  const key = "/" + path.relative("public", file).split(path.sep).join("/");
  manifest[key] = { width: targetW, height: outH };
  originalBytes += statSync(file).size;
  webpBytes += info.size;
}

const header =
  "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n" +
  "// Intrinsic dimensions of each optimized image, keyed by public path.\n" +
  "// Used by <Img> to reserve space and prevent layout shift.\n\n";
const body =
  "export const imageManifest: Record<string, { width: number; height: number }> = " +
  JSON.stringify(manifest, null, 2) +
  ";\n";
await writeFile("src/data/imageManifest.ts", header + body);

const mb = (b) => (b / 1024 / 1024).toFixed(2);
console.log(
  `Optimized ${files.length} images -> WebP: ${mb(originalBytes)}MB source, ${mb(webpBytes)}MB webp ` +
    `(${Math.round((1 - webpBytes / originalBytes) * 100)}% smaller). Manifest: src/data/imageManifest.ts`,
);
