// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions of each optimized image, keyed by public path.
// Used by <Img> to reserve space and prevent layout shift.

export const imageManifest: Record<string, { width: number; height: number }> = {};
