// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions of each optimized image, keyed by public path.
// Used by <Img> to reserve space and prevent layout shift.

export const imageManifest: Record<string, { width: number; height: number }> = {
  "/case-studies/aria-health/chat.jpg": {
    "width": 1400,
    "height": 875
  },
  "/case-studies/aria-health/dashboard.jpg": {
    "width": 1400,
    "height": 875
  },
  "/case-studies/aria-health/hero.jpg": {
    "width": 1400,
    "height": 875
  },
  "/case-studies/aria-health/journey.jpg": {
    "width": 1400,
    "height": 875
  },
  "/case-studies/gardenhq/bed.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/gardenhq/hero.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/gardenhq/map.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/helm/ai-edits.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/helm/hero.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/hikerlink/check-in.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/hikerlink/emergency.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/hikerlink/hero.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/hikerlink/trail-feed.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/lila-trips/destination-guide.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/lila-trips/hero.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/lila-trips/planner.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/lila-trips/practice-companion.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/lila-yoga/hero.jpg": {
    "width": 1600,
    "height": 900
  },
  "/case-studies/lila-yoga/meditation-card.jpg": {
    "width": 1600,
    "height": 900
  },
  "/case-studies/lila-yoga/movement-card.jpg": {
    "width": 1600,
    "height": 900
  },
  "/case-studies/lila-yoga/vocabulary-card.jpg": {
    "width": 1600,
    "height": 900
  },
  "/case-studies/plainly/conversation.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/plainly/hero.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/plainly/profile.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/plainly/your-turn.jpg": {
    "width": 1600,
    "height": 1422
  },
  "/case-studies/san-juan-boating-guide/hero.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/san-juan-boating-guide/map.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/san-juan-boating-guide/marina.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/san-juan-boating-guide/restaurant.jpg": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/utah-trip-guide/booking-hotel-cliffrose.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/utah-trip-guide/cards-narrows-day.png": {
    "width": 1600,
    "height": 999
  },
  "/case-studies/utah-trip-guide/hero-cover-route.png": {
    "width": 1600,
    "height": 1000
  },
  "/case-studies/utah-trip-guide/weather-flash-flood.png": {
    "width": 1600,
    "height": 1000
  }
};
